package hooks

import (
	"fmt"
	"os"
	"path/filepath"
)

// InstallOptions configures pre-commit hook installation.
type InstallOptions struct {
	// PreCommitOptions configures the hook behavior.
	*PreCommitOptions

	// Force overwrites an existing hook.
	Force bool

	// GitDir is the path to the .git directory.
	// If empty, FindGitDir is used to locate it.
	GitDir string
}

// DefaultInstallOptions returns default installation options.
func DefaultInstallOptions() *InstallOptions {
	return &InstallOptions{
		PreCommitOptions: DefaultPreCommitOptions(),
		Force:            false,
	}
}

// InstallPreCommit installs the pre-commit hook in the git repository.
func InstallPreCommit(opts *InstallOptions) error {
	if opts == nil {
		opts = DefaultInstallOptions()
	}

	// Find git directory
	gitDir := opts.GitDir
	if gitDir == "" {
		var err error
		gitDir, err = FindGitDir()
		if err != nil {
			return err
		}
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	hookPath := filepath.Join(hooksDir, "pre-commit")

	// Check for existing hook
	if _, err := os.Stat(hookPath); err == nil {
		if !opts.Force {
			return fmt.Errorf("pre-commit hook already exists at %s (use --force to overwrite)", hookPath)
		}
	}

	// Create hooks directory if needed
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("creating hooks directory: %w", err)
	}

	// Generate script
	script, err := GeneratePreCommitScript(opts.PreCommitOptions)
	if err != nil {
		return fmt.Errorf("generating script: %w", err)
	}

	// Write hook file
	//nolint:gosec // G306: Executable permission is intentional for git hook
	if err := os.WriteFile(hookPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("writing hook: %w", err)
	}

	return nil
}

// FindGitDir searches for the .git directory starting from the current directory.
func FindGitDir() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getting working directory: %w", err)
	}

	for {
		gitPath := filepath.Join(dir, ".git")

		// Check if .git exists
		info, err := os.Stat(gitPath)
		if err == nil {
			if info.IsDir() {
				return gitPath, nil
			}
			// .git could be a file (for worktrees), read it to find the actual git dir
			// For simplicity, we'll just treat this as the git dir location
			return gitPath, nil
		}

		// Move up one directory
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	return "", fmt.Errorf("not a git repository (or any parent up to mount point)")
}

// UninstallPreCommit removes the pre-commit hook if it was installed by api-style.
func UninstallPreCommit() error {
	gitDir, err := FindGitDir()
	if err != nil {
		return err
	}

	hookPath := filepath.Join(gitDir, "hooks", "pre-commit")

	// Check if hook exists
	data, err := os.ReadFile(hookPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("no pre-commit hook found")
		}
		return fmt.Errorf("reading hook: %w", err)
	}

	// Check if it's our hook
	if !isAPIStyleHook(string(data)) {
		return fmt.Errorf("pre-commit hook was not installed by api-style")
	}

	// Remove the hook
	if err := os.Remove(hookPath); err != nil {
		return fmt.Errorf("removing hook: %w", err)
	}

	return nil
}

// isAPIStyleHook checks if the script content indicates it was generated by api-style.
func isAPIStyleHook(content string) bool {
	return len(content) > 0 && (containsStr(content, "systemspec-apistyle pre-commit hook") ||
		containsStr(content, "api-style hooks init"))
}

// containsStr is a simple string contains helper.
func containsStr(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr || len(s) > 0 && findSubstr(s, substr))
}

func findSubstr(s, substr string) bool {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}
