package hooks

import (
	"fmt"
	"strings"
	"text/template"
)

// PreCommitOptions configures the pre-commit hook.
type PreCommitOptions struct {
	// Profile is the style profile to use for linting.
	Profile string

	// Level is the conformance level to enforce.
	Level string

	// FailOnWarnings causes the hook to fail on warnings, not just errors.
	FailOnWarnings bool
}

// DefaultPreCommitOptions returns default pre-commit options.
func DefaultPreCommitOptions() *PreCommitOptions {
	return &PreCommitOptions{
		Profile:        "default",
		Level:          "",
		FailOnWarnings: false,
	}
}

// GeneratePreCommitScript generates the pre-commit hook script.
func GeneratePreCommitScript(opts *PreCommitOptions) (string, error) {
	if opts == nil {
		opts = DefaultPreCommitOptions()
	}

	tmpl, err := template.New("precommit").Parse(preCommitScriptTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, opts); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}

	return buf.String(), nil
}

// preCommitScriptTemplate is the template for the pre-commit hook.
const preCommitScriptTemplate = `#!/bin/bash
# systemspec-apistyle pre-commit hook
# Generated by: api-style hooks init
#
# This hook lints staged OpenAPI/Swagger files before committing.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Find api-style binary
API_STYLE=""
if command -v api-style &> /dev/null; then
    API_STYLE="api-style"
elif [ -x "./bin/api-style" ]; then
    API_STYLE="./bin/api-style"
elif [ -x "./api-style" ]; then
    API_STYLE="./api-style"
fi

if [ -z "$API_STYLE" ]; then
    echo -e "${YELLOW}Warning: api-style not found, skipping lint${NC}"
    exit 0
fi

# Get staged OpenAPI/Swagger files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -iE '\.(yaml|yml|json)$' | grep -iE '(openapi|swagger|api)' || true)

if [ -z "$STAGED_FILES" ]; then
    # No OpenAPI files staged, nothing to do
    exit 0
fi

echo "Linting staged OpenAPI specifications..."

FAILED=0
for FILE in $STAGED_FILES; do
    if [ ! -f "$FILE" ]; then
        continue
    fi

    echo -n "  Checking $FILE... "

    # Build lint command
    LINT_CMD="$API_STYLE lint \"$FILE\""
    {{- if .Profile }}
    LINT_CMD="$LINT_CMD --profile {{.Profile}}"
    {{- end }}
    {{- if .Level }}
    LINT_CMD="$LINT_CMD --level {{.Level}}"
    {{- end }}

    # Run lint and capture output
    if OUTPUT=$(eval "$LINT_CMD" 2>&1); then
        echo -e "${GREEN}OK${NC}"
    else
        EXIT_CODE=$?
        echo -e "${RED}FAILED${NC}"
        echo "$OUTPUT" | head -50
        FAILED=1
    fi
done

if [ $FAILED -eq 1 ]; then
    echo ""
    echo -e "${RED}Pre-commit hook failed: API style violations found${NC}"
    echo "Fix the issues above or use 'git commit --no-verify' to skip (not recommended)"
    exit 1
fi

echo -e "${GREEN}All OpenAPI specifications passed linting${NC}"
exit 0
`
